### PR TITLE
upgrade PostgreSQL version to 12

### PR DESCRIPTION
**Pull request by fbalicchia**
Hi, @dasmdasm could please review this Pr? Basically, it upgrades Postgre version from 11 to 12. After this 
we can go forward with [pr]( https://github.com/google/differential-privacy/pull/98)
Thanks

### CODE REVIEW

**Comment by dasmdasm** [comment]
Looks good, I'll merge this as soon as we finish with our in-progress push.

**Review by jheng21 — CHANGES_REQUESTED** [review]
​workspace​(​name​ ​=​ ​"cpp_exp"​) 
 ​load​( 
 ​    ​"@bazel_tools//tools/build_defs/repo:git.bzl"​, 
 ​    ​"git_repository"​, 
 ​) 
  
 ​git_repository​( 
 ​    ​name​ ​=​ ​"com_google_absl"​, 
 ​    ​remote​ ​=​ ​"https://github.com/abseil/abseil-cpp.git"​, 
 ​    ​tag​ ​=​ ​"20200225.2"​, 
 ​) 
  
 ​git_repository​( 
 ​    ​name​ ​=​ ​"com_google_googletest"​, 
 ​    ​remote​ ​=​ ​"https://github.com/google/googletest.git"​, 
 ​    ​tag​ ​=​ ​"release-1.8.1"​, 
 ​)

**Comment by fbalicchia** [comment]
@jheng21 Could you please elaborate more on your suggestion,? At the moment of writing seems that the versions about `google test` and `absl` are newer than your suggestion or do you want a simple change in reference type?

**Review by jheng21 — APPROVED** [review]

**Comment by dasmdasm** [comment]
Sorry, we get occasional spam, this appears to be more of that. There doesn't appear to be a way to delete it, so please ignore it.

**Pull request merged**
